### ISSUE TITLE
Add Next Birthday Countdown:

### ISSUE THREAD

**Issue by ShadBalti** [ShadBalti/Age-Calculator-App#24]
Display a countdown to the user's next birthday, showing the remaining days, hours, minutes, and seconds.

**Comment by SapirKro** [comment]
Can you please assign the issue to me?

**Comment by ShadBalti** [comment]
Okay 🆗

**Comment by SharifAly** [comment]
i want contribute to this issue

**Comment by huzaifaazim0** [comment]
is this completed?
if not let me add it

**Comment by huzaifaazim0** [comment]
Thanks. i will get to it

**Comment by huzaifaazim0** [comment]
Added
created a pull request
https://github.com/ShadBalti/Age-Calculator-App/pull/26
