### ISSUE TITLE
Good first issues

### ISSUE THREAD

**Issue by ShadBalti** [ShadBalti/Age-Calculator-App#3]

**Comment by pawarsshruti** [comment]
hey, would like to work on this, could you please assign?

**Comment by ShadBalti** [comment]
> Hi, Its my first issue...

Hi

**Welcome to your first issue! I'm so glad you're interested in contributing to the project.**

I know it can be intimidating to work on your first issue, but don't worry. I'm here to help!

Here are some tips to get you started:

1. Read the issue description carefully. Make sure you understand what the problem is and what the expected solution is.
2. If you have any questions, don't hesitate to ask. I'm happy to help in any way that I can.
3. Start small. Don't try to solve the entire problem at once. Break it down into smaller, more manageable tasks.
4. Test your code thoroughly. Before you submit a pull request, make sure to test your code thoroughly to make sure that it works as expected.
5. I'm confident that you can do this! Just take your time and ask for help when you need it.

Best,
ShadBalti

**Comment by jsho982045** [comment]
Hello I would like to work on this issue as well. Can you please assign?

**Comment by ShadBalti** [comment]
Okay 👍👍

**Comment by ShadBalti** [comment]
# Everyone feel free to contribute

**Comment by juliajobczyk** [comment]
Hi can I also be assigned please?

**Comment by Sh1vd3v** [comment]
hi @ShadBalti  where is the issue description, can you please share the issue description, i seem to be missing the description?

**Comment by AnushkaSharma04** [comment]
Hi I would like to contribute . But missing the issue description . Can u please provide that ?

**Comment by ShadBalti** [comment]
> hy, i want to contribute to this issue.

https://github.com/ShadBalti/Age-Calculator-App/issues/24

**Comment by Anujesh-Ansh** [comment]
Hi, I too want to contribute to solve the issue, but I'm unable to view the issue description.
