### ISSUE TITLE
Calculate age button do not work after "Please enter a valid birthdate." error

### ISSUE THREAD

**Issue by thesohailjafri** [ShadBalti/Age-Calculator-App#4]
**Describe the bug**
After the warning of "Please enter a valid birthdate." calculate age button do not work even with valid birthdate

**To Reproduce**
1. Select an invalid date i.e date of future 
3. Click on the calculate button
4. Select a valid date i.e date of today or past
5. It does not show output

**Expected behavior**
It should show the calculated data after reproducing the issue

**Video Demo**
https://github.com/ShadBalti/Age-Calculator-App/assets/66732877/957f30df-0468-4d21-abb0-0d8fee68274e

**Desktop**
 - Windows
 - Browser Chrome

**Comment by thesohailjafri** [comment]
I would like to solve this bug so please assign this to me

**Comment by ShadBalti** [comment]
Yeah that's is a problem

**Comment by thesohailjafri** [comment]
Can I fix this issue, if you don't mind

**Comment by ShadBalti** [comment]
Okay 😊👌
